spring:
  cache:
    type: redis
  redis:
    host: 172.16.96.57 # server host
    port: 8802 # Redis服务器连接端口
    timeout: 30000 # 连接超时时间（毫秒）
    database: 0
    cluster:
      max-redirects: 3
      nodes:
      - 172.16.96.57:8801,172.16.96.57:8802,172.16.96.57:8803,172.16.96.57:8804,172.16.96.57:8805,172.16.96.57:8806
    lettuce: 
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 1 # 连接池中的最小空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
  zipkin:
    base-url: http://localhost:9411/ # 指定了 Zipkin 服务器的地址
#  rabbitmq:
#    host: 172.16.97.114
#    port: 5672
#    username: admin
#    password: admin 